title: ProductVariant
type: object
description: |-
  ### Available includes

  - products
  - basketLines
  - image
  - tax
  - customerPricing
  - tiers
properties:
  id:
    type: string
  sku:
    type: string
  backorder:
    type: string
  requires_shipping:
    type: boolean
  price:
    type: number
  factor_tax:
    type: number
  unit_price:
    type: number
  total_tax:
    type: number
  unit_tax:
    type: number
  unit_qty:
    type: integer
  min_qty:
    type: integer
  max_qty:
    type: integer
  min_batch:
    type: integer
  inventory:
    type: integer
  incoming:
    type: integer
  group_pricing:
    type: boolean
  weight:
    type: object
    properties:
      value:
        type: string
      unit:
        type: string
  height:
    type: object
    properties:
      value:
        type: string
      unit:
        type: string
  width:
    type: object
    properties:
      value:
        type: string
      unit:
        type: string
  depth:
    type: object
    properties:
      value:
        type: string
      unit:
        type: string
  volume:
    type: object
    properties:
      value:
        type: string
      unit:
        type: string
  product:
    $ref: '#/components/schemas/ProductResponse'
  image:
    $ref: '#/components/schemas/AssetResponse'
  customer_pricing:
    $ref: '#/components/schemas/CustomerPriceCollection'
  tax:
    $ref: '#/components/schemas/TaxResponse'
  tiers:
    $ref: '#/components/schemas/ProductTierPriceCollection'
  options:
    type: object
