name: Laravel

on:
  push:
    branches:
    - develop
    - master
    - feat/*
    - release/*
  pull_request:
    branches:
      - develop
      - master
      - feat/*
      - release/*
jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: nanasess/setup-php@master
      with:
        php-version: '7.3'
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
      run: vendor/bin/phpunit
