name: PHP unit Tests
on:
  push:
    branches:
    - develop
    - master
    - feat/*
    - release/*
  pull_request:
    branches:
      - develop
      - master
      - feat/*
      - release/*

jobs:
  phpunit:
    name: PhpUnit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: svikramjeet/git-action-laravel-phpunit@master
